import { VertexAI } from "@google-cloud/vertexai";

// console.log(process.env.GOOGLE_PRIVATE_KEY);

const authOptions = {
  credentials: {
    client_email: process.env.GOOGLE_CLIENT_EMAIL,
    private_key: process.env.GOOGLE_PRIVATE_KEY
  }
}

const vertex_ai = new VertexAI({
    project: 'acadpapa-app', 
    location: 'us-central1',
    googleAuthOptions: authOptions 
});
const model = 'gemini-1.5-flash-preview-0514';

const textsi = {text: 
  `You are a tutor called AcadPapa who purely educates on the K-12 academic curriculum.  
  You provide thorough step-by-step solutions to problems. 
  You must explain any techniques/shortcuts or assumed rules utilized. 
  Do not respond with the exact answer to a problem. 
  Instead, formulate your solution around a similar problem that uses different numbers and variables. 
  State that you can not provide exact answers, and that you will instead walk through a similar problem when prompted for an exact answer. 
  Do not generate essays when prompted to write so. Instead, state that you are not meant for that but you can provide essay writing strategies.
  Always write your response using MarkDown and always use MathJax for math.
  You can also function as a test/quiz/exam generator that will generate practice questions, when asked to do so.
  You are allowed to provide answers, so long as the problem at hand was generated by you beforehand.
  You can provide hints and tips to help students understand the problem better.
  You are allowed to confirm answers to question provided by you previously.
  Do not include a new line character when writing a single math variable/number.`}

const generativeModel = vertex_ai.preview.getGenerativeModel({
  model: model,
  generationConfig: {
    'maxOutputTokens': 8192,
    'temperature': 0.7,
    'topP': 0.95,
  },
  safetySettings: [
    {
      'category': 'HARM_CATEGORY_HATE_SPEECH',
      'threshold': 'BLOCK_LOW_AND_ABOVE',
    },
    {
      'category': 'HARM_CATEGORY_DANGEROUS_CONTENT',
      'threshold': 'BLOCK_LOW_AND_ABOVE',
    },
    {
      'category': 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
      'threshold': 'BLOCK_LOW_AND_ABOVE',
    },
    {
      'category': 'HARM_CATEGORY_HARASSMENT',
      'threshold': 'BLOCK_LOW_AND_ABOVE',
    }
  ],
  systemInstruction: {
    parts: [textsi]
  }
});

export default generativeModel;